### ISSUE TITLE
mrbod fails: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by htgoebel** [domenkozar/mr.bob#89]
When I try to setup a template using mrbob, mrbob crashes with (full traceback see below):
```
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

How to reproduce:
```
virtualenv --python /usr/bin/python3.7 /tmp/mrbobvenv
cd /tmp/mrbobvenv
bin/pip install mr.bob bobtemplates.plone
bin/mrbob -O plonetheme.tango bobtemplates:plone_addon
bin/mrbob -O plonetheme.tango bobtemplates:plone_addon
```
Traceback:
```
Traceback (most recent call last):
  File "bin/mrbob", line 10, in <module>
    sys.exit(main())
  File "/tmp/mrbobvenv/lib/python3.7/site-packages/mrbob/cli.py", line 155, in main
    defaults=defaults)
  File "/tmp/mrbobvenv/lib/python3.7/site-packages/mrbob/configurator.py", line 138, in __init__
    self.template_dir, self.is_tempdir = parse_template(template)
  File "/tmp/mrbobvenv/lib/python3.7/site-packages/mrbob/configurator.py", line 92, in parse_template
    path = resolve_dotted_path(template_name)
  File "/tmp/mrbobvenv/lib/python3.7/site-packages/mrbob/configurator.py", line 40, in resolve_dotted_path
    return os.path.join(os.path.dirname(module.__file__), dir_name)
  File "/tmp/mrbobvenv/lib64/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by htgoebel** [comment]
I digged a bit into this and discovered that `bobtemplates? is a namespace module:
```
> /tmp/mrbobenv/lib/python3.7/site-packages/mrbob/configurator.py(40)resolve_dotted_path()
-> return os.path.join(os.path.dirname(module.__file__), dir_name)
(Pdb) p module
<module 'bobtemplates' (namespace)>
```

### Expected behavior

mrbob should catch this case and fail with a meaningfull error message.

I assume this error is caused by changing the structure of  the `bobtemplates` packages. Thus the error message could mention this detail a a possible cause.

**Comment by mck9** [comment]
Maybe the Plone documentation should be fixed instead. This works:

`bin/mrbob -O plonetheme.tango bobtemplates.plone:addon`
